app:
  host: localhost
  port: 8109
  root: /auth

siam:
  base_url: $SIAM_URL
  aselect_server: $SIAM_A_SELECT_SERVER
  app_id: $SIAM_APP_ID
  shared_secret: $SIAM_SHARED_SECRET

jwt:
  refreshtokens:
    secret: $JWT_REFRESH_SECRET
    algorithm: HS256
    lifetime: 2592000  # 30 x 24 x 3600
  accesstokens:
    secret: $JWT_ACCESS_SECRET
    algorithm: HS256
    lifetime: 300

postgres:
  host: $PG_HOST
  port: $PG_PORT
  user: $PG_USER
  password: $PG_PASS
  dbname: $PG_DB
