app:
  host: localhost
  port: 8109
  root: /auth

siam:
  base_url: ${SIAM_URL:- }
  aselect_server: ${SIAM_A_SELECT_SERVER:- }
  app_id: ${SIAM_APP_ID:- }
  shared_secret: ${SIAM_SHARED_SECRET:- }

# Temporary, as a replacement for client registration (rfc6749#section-2)
allowed_callback_hosts:
  amsterdam.nl:
    - https
  localhost:
    - http

jwt:
  refreshtokens:
    secret: $JWT_REFRESH_SECRET
    algorithm: HS256
    lifetime: ${JWT_LIFETIME:-43200}  # 12 x 3600
  accesstokens:
    secret: $JWT_ACCESS_SECRET
    algorithm: HS256
    lifetime: 300

postgres:
  host: ${DB_HOST:-localhost}
  port: ${DB_PORT:-5432}
  user: ${DB_USER:-authuser}
  password: ${DB_PASS:-authpassword}
  dbname: ${DB_DATABASE:-authz}

logging:
  version: 1
  formatters:
    root:
      (): logstash_formatter.LogstashFormatterV1
    auditlog:
      (): logstash_formatter.LogstashFormatterV1
      fmt: '{"extra": {"logtype": "auditlog"}}'
  handlers:
    root:
      class : logging.StreamHandler
      formatter: root
    auditlog:
      class : logging.StreamHandler
      formatter: auditlog
  loggers:
    auditlog.authserver:
      level: DEBUG
      propagate: false
      handlers:
        - auditlog
    authserver:
      level: ${LOGLEVEL:-DEBUG}
      propagate: false
      handlers:
        - root
  root:
    level: ${LOGLEVEL:-DEBUG}
    handlers:
      - root
