app:
  host: localhost
  port: 8109
  root: /auth

# Allowed redirect prefixes
callbacks:
  - https://acc.api.data.amsterdam.nl/oauth2/callback
  - https://api.data.amsterdam.nl/oauth2/callback
  - http://localhost

jwt:
  secret: $JWT_REFRESH_SECRET
  algorithm: HS256
  lifetime: ${JWT_LIFETIME:-10}

postgres:
  host: ${DB_HOST:-localhost}
  port: ${DB_PORT:-5432}
  user: ${DB_USER:-dpuser}
  password: ${DB_PASS:-dpuser}
  dbname: ${DB_DATABASE:-accounts}

logging:
  version: 1
  formatters:
    root:
      format: "%(asctime)s	%(name)s %(levelname)s (%(pathname)s/%(filename)s:%(funcName)s@%(lineno)d): %(message)s"
    auditlog:
      format: "%(asctime)s	%(name)s %(levelname)s (pid: %(process)d | ts: %(created)f) %(message)s"
  handlers:
    local-root:
      class: logging.StreamHandler
      formatter: root
    local-auditlog:
      class: logging.StreamHandler
      formatter: auditlog
    gelf-root:
      class : graypy.GELFUDPHandler
      formatter: root
      host: ${LOGSTASH_HOST:-localhost}
      port: ${LOGSTASH_GELF_UDP_PORT:-12201}
    gelf-auditlog:
      class : graypy.GELFUDPHandler
      formatter: auditlog
      host: ${LOGSTASH_HOST:-localhost}
      port: ${LOGSTASH_UDP_PORT:-12201}
  loggers:
    authserver:
      level: ${LOGLEVEL:-DEBUG}
      propagate: false
      handlers:
        - local-root
        - gelf-root
    auditlog.authserver:
      level: DEBUG
      propagate: false
      handlers:
        - local-auditlog
        - gelf-auditlog
  root:
    level: ${LOGLEVEL:-DEBUG}
    handlers:
      - local-root
      - gelf-root
