app:
  host: localhost
  port: 8109
  root: /auth

siam:
  base_url: ${SIAM_URL:- }
  aselect_server: ${SIAM_A_SELECT_SERVER:- }
  app_id: ${SIAM_APP_ID:- }
  shared_secret: ${SIAM_SHARED_SECRET:- }

# Temporary, as a replacement for client registration (rfc6749#section-2)
allowed_callback_hosts:
  amsterdam.nl:
    - https
  localhost:
    - http

jwt:
  refreshtokens:
    secret: $JWT_REFRESH_SECRET
    algorithm: HS256
    lifetime: ${JWT_LIFETIME:-43200}  # 12 x 3600
  accesstokens:
    secret: $JWT_ACCESS_SECRET
    algorithm: HS256
    lifetime: 300

postgres:
  host: ${DB_HOST:-localhost}
  port: ${DB_PORT:-5432}
  user: ${DB_USER:-authuser}
  password: ${DB_PASS:-authpassword}
  dbname: ${DB_DATABASE:-authz}

logging:
  version: 1
  formatters:
    root:
      format: "%(asctime)s	%(name)s %(levelname)s (%(pathname)s/%(filename)s:%(funcName)s@%(lineno)d): %(message)s"
    auditlog:
      format: "%(asctime)s	%(name)s %(levelname)s (pid: %(process)d | ts: %(created)f) %(message)s"
  handlers:
    local-root:
      class: logging.StreamHandler
      formatter: root
    local-auditlog:
      class: logging.StreamHandler
      formatter: auditlog
    gelf-root:
      class : graypy.GELFHandler
      formatter: root
      host: ${LOGSTASH_HOST:-localhost}
      port: ${LOGSTASH_GELF_UDP_PORT:-12201}
    gelf-auditlog:
      class : graypy.GELFHandler
      formatter: auditlog
      host: ${LOGSTASH_HOST:-localhost}
      port: ${LOGSTASH_UDP_PORT:-12201}
  loggers:
    authserver:
      level: ${LOGLEVEL:-DEBUG}
      propagate: false
      handlers:
        - local-root
        - gelf-root
    auditlog.authserver:
      level: DEBUG
      propagate: false
      handlers:
        - local-auditlog
        - gelf-auditlog
  root:
    level: ${LOGLEVEL:-DEBUG}
    handlers:
      - local-root
      - gelf-root
