auth:
  build: .
  ports:
    - "8109:8000"
  environment:
    - DEBUG
    - SIAM_URL
    - SIAM_A_SELECT_SERVER
    - SIAM_APP_ID
    - SIAM_SHARED_SECRET
    - JWT_SHARED_SECRET_KEY
    - JWT_LIFETIME
  command: /bin/sh /app/docker-entrypoint.sh
