auth:
  build: .
  ports:
    - "8109:8000"
  environment:
    - SIAM_URL
    - SIAM_A_SELECT_SERVER
    - SIAM_APP_ID
    - SIAM_SHARED_SECRET
    - JWT_REFRESH_SECRET
    - JWT_ACCESS_SECRET
    - PG_HOST
    - PG_PORT
    - PG_USER
    - PG_PASS
    - PG_DB
  command: make -C /app run

database:
  image: postgres:9.5
  ports:
    - "5432:5432"
  environment:
    - POSTGRES_DB=authz
    - POSTGRES_USER=authuser
    - POSTGRES_PASSWORD=authpassword
