auth:
  build: .
  ports:
    - "8102:8000"
  environment:
    - DEBUG
    - PREFERRED_URL_SCHEME
    - SECRET_KEY
    - SIAM_URL
    - SIAM_A_SELECT_SERVER
    - SIAM_APP_ID
    - SIAM_SHARED_SECRET
