version: '3.0'
services:
  database:
    image: postgres:9.5
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: accounts
      POSTGRES_USER: dpuser
      POSTGRES_PASSWORD: dpuser

  auth:
    build: .
    links:
      - database:database
    ports:
      - "8000:8000"
    environment:
      JWT_REFRESH_SECRET: refreshsecret
      DB_HOST: database
      UWSGI_HTTP: ":8000"
      UWSGI_MODULE: auth.server
      UWSGI_CALLABLE: app
      UWSGI_MASTER: 1
      UWSGI_PROCESSES: 4
      UWSGI_LAZY_APPS: 1
