auth:
  build: .
  ports:
    - "8109:8000"
  environment:
    - DEBUG
    - AUTH_SKIP_CONF_CHECK
    - SIAM_URL
    - SIAM_A_SELECT_SERVER
    - SIAM_APP_ID
    - SIAM_SHARED_SECRET
    - JWT_SHARED_SECRET_KEY
    - JWT_LIFETIME
  command: make -C /app run-uwsgi
