auth-acc:
  build: ../
  environment:
    - DEBUG=true
    - SIAM_URL
    - SIAM_A_SELECT_SERVER
    - SIAM_APP_ID
    - SIAM_SHARED_SECRET
    - JWT_SHARED_SECRET_KEY
    - JWT_LIFETIME
  command: make -C /app test

