database:
  image: admin.datapunt.amsterdam.nl:5000/atlas/postgres
  environment:
    POSTGRES_PASSWORD: insecure
    POSTGRES_USER: auths

tests:
  build: ../web
  links:
    - database:database
  environment:
    DATABASE_NAME: auths
    DATABASE_USER: auths
    DATABASE_PASSWORD: insecure
  command: bash -c "/app/docker-wait.sh && python manage.py jenkins"
